// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameCfgCurrency = "cfg_currency"

// CfgCurrency mapped from table <cfg_currency>
type CfgCurrency struct {
	ID        int64  `gorm:"column:id;primaryKey" json:"id"`  // 币种类型
	Currency  string `gorm:"column:currency" json:"currency"` // 币别
	Icon      string `gorm:"column:icon" json:"icon"`
	Precision int8   `gorm:"column:precision;not null" json:"precision"` // 保留小数位数
}

// TableName CfgCurrency's table name
func (*CfgCurrency) TableName() string {
	return TableNameCfgCurrency
}
